#!/usr/bin/env python3
"""Sync the vendored Game Data snapshot from an Idle Fantasy checkout.

Game Data is vendored rather than fetched at runtime so the app is reproducible,
works offline, and shows a reviewable diff when the game's data changes.

Usage:
    scripts/sync-game-data.py --source ~/Desktop/IdleFantasy      # refresh the snapshot
    scripts/sync-game-data.py --source ~/Desktop/IdleFantasy --check   # report drift only

--check exits 1 when the snapshot is stale, so CI can gate on it.
"""

from __future__ import annotations

import argparse
import hashlib
import json
import re
import shutil
import subprocess
import sys
from pathlib import Path

REPO_ROOT = Path(__file__).resolve().parent.parent
VENDOR_DIR = REPO_ROOT / "vendor" / "game-data"
MANIFEST = VENDOR_DIR / "manifest.json"

# Only what v1 actually needs. Each entry is a path relative to the game's
# assets/data/ directory. Keep this list minimal: every file added here ships
# to every user on first load.
FILES = [
    # Ledger categories
    "enemies.json",        # monsters never killed
    "quests.json",         # main quests; also the filter that separates main
                           # quests from the dailies/weeklies/guild quests that
                           # also appear in a save's questProgress
    "raid_bosses.json",    # boss items never obtained
    "equipment.json",      # equipment Ledger, and fishing_efficiency for rods
    # Projection: expected items per Session, fishing sharks
    "fish.json",           # raw_shark stats
    "skills/fishing.json",  # level-tiered drop tables
    # Modifiers
    "prestige_paths.json",  # prestige node definitions behind toolEffMultiplier
]

# Deliberately NOT vendored:
#   xp_table.json          - XpTable is a closed-form formula; ported, not loaded
#   items.json             - unreferenced by the game
#   guild_*_quests.json    - ~300 KB; filtering questProgress against quests.json
#                            is enough to isolate main quests
#   house_tiles.json, official_themes.json - no Ledger or Projection uses them


def game_version(source: Path) -> dict:
    """Read the game's version from its Gradle build file, plus its git commit."""
    gradle = (source / "app" / "build.gradle.kts").read_text()
    code = re.search(r"versionCode\s*=\s*(\d+)", gradle)
    name = re.search(r'versionName\s*=\s*"([^"]+)"', gradle)
    try:
        commit = subprocess.run(
            ["git", "-C", str(source), "rev-parse", "HEAD"],
            capture_output=True, text=True, check=True,
        ).stdout.strip()
    except (subprocess.CalledProcessError, FileNotFoundError):
        commit = None
    return {
        "version_code": int(code.group(1)) if code else None,
        "version_name": name.group(1) if name else None,
        "commit": commit,
    }


def digest(path: Path) -> str:
    return hashlib.sha256(path.read_bytes()).hexdigest()


def build_manifest(source: Path) -> dict:
    data_dir = source / "app" / "src" / "main" / "assets" / "data"
    missing = [f for f in FILES if not (data_dir / f).is_file()]
    if missing:
        sys.exit(f"error: not found in {data_dir}: {', '.join(missing)}")
    return {
        "_comment": (
            "Generated by scripts/sync-game-data.py. Game Data is vendored from "
            "tristinbaker/IdleFantasy (GPL-3.0) and kept unmodified. Do not edit by hand."
        ),
        "source": "https://github.com/tristinbaker/IdleFantasy",
        "game": game_version(source),
        "files": {f: digest(data_dir / f) for f in FILES},
    }


def main() -> int:
    ap = argparse.ArgumentParser(description=__doc__)
    ap.add_argument("--source", required=True, type=Path,
                    help="path to an IdleFantasy checkout")
    ap.add_argument("--check", action="store_true",
                    help="report drift without writing; exit 1 if stale")
    args = ap.parse_args()

    source = args.source.expanduser().resolve()
    if not (source / "app" / "src" / "main" / "assets" / "data").is_dir():
        return int(bool(sys.stderr.write(
            f"error: {source} does not look like an IdleFantasy checkout\n")))

    fresh = build_manifest(source)

    if args.check:
        if not MANIFEST.is_file():
            print("stale: no manifest; run without --check to create the snapshot")
            return 1
        current = json.loads(MANIFEST.read_text())
        drift = [f for f, h in fresh["files"].items()
                 if current.get("files", {}).get(f) != h]
        gone = set(current.get("files", {})) - set(fresh["files"])
        if not drift and not gone and current.get("game") == fresh["game"]:
            print(f"up to date with game {fresh['game']['version_name']} "
                  f"({fresh['game']['version_code']})")
            return 0
        if current.get("game") != fresh["game"]:
            print(f"game version changed: {current.get('game')} -> {fresh['game']}")
        for f in drift:
            print(f"changed: {f}")
        for f in sorted(gone):
            print(f"no longer vendored: {f}")
        print("\nsnapshot is stale; re-run without --check, then review the diff")
        return 1

    data_dir = source / "app" / "src" / "main" / "assets" / "data"
    for f in FILES:
        dest = VENDOR_DIR / f
        dest.parent.mkdir(parents=True, exist_ok=True)
        shutil.copy2(data_dir / f, dest)
    MANIFEST.write_text(json.dumps(fresh, indent=2) + "\n")

    total = sum((VENDOR_DIR / f).stat().st_size for f in FILES)
    print(f"synced {len(FILES)} files ({total / 1024:.0f} KB) from game "
          f"{fresh['game']['version_name']} ({fresh['game']['version_code']})")
    if fresh["game"]["commit"]:
        print(f"upstream commit {fresh['game']['commit'][:12]}")
    print("review the diff before committing — a data change can move every projection")
    return 0


if __name__ == "__main__":
    sys.exit(main())
